---
- name: omero searchengine | Create Nginx configuration directory
  become: true
  ansible.builtin.file:
    path: "{{ apps_folder }}/searchengine/nginx/conf.d"
    state: directory
    owner: 1000
    group: root
    mode: 0644
  changed_when: false

- name: omero searchengine | Create Nginx log directory
  become: true
  ansible.builtin.file:
    path: "{{ apps_folder }}/searchengine/nginx/log"
    state: directory
    owner: 1000
    group: root
    mode: 0755
  changed_when: false

- name:  omero searchengine | Copy serachengine Nginx config
  become: true
  ansible.builtin.template:
    dest: "{{ apps_folder }}/searchengine/nginx/conf.d/searchengine.conf"
    src: searchengine.conf.j2
    owner: root
    group: root
    mode: 0644
  changed_when: false

- name: omero searchengine | Run Nginx container
  become: true
  community.docker.docker_container:
    name: searchengine-nginx-container
    image: nginx:latest
    networks:
      - name: host

    published_ports:
      - "{{ NGINX_PORT }}:{{ NGINX_PORT }}"
    volumes:
      - "{{ apps_folder }}/searchengine/nginx/conf.d/searchengine.conf:/etc/nginx/conf.d/searchengine.conf"
      - "{{ apps_folder }}/searchengine/nginx/log:/var/log/nginx"
      - "{{ apps_folder }}/data_dump:{{ DATA_DUMP_FOLDER }}"
    state: started
    restart_policy: always
  tags: [always, nginx]



# always qq